# Generated by Django 4.2.5 on 2023-10-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='name',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheese',
            name='origin_country',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheese',
            name='type',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
    ]
